steps:

  - # Uses the Cloud Builder Gradle image since it is cached.
    name: 'gcr.io/cloud-builders/gradle'
    id: 'Cache'
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        mkdir .docker &&
        ln -s $$HOME/.docker/config.json .docker/config.json

  - # Compiles the app and Jib build.
    name: 'gcr.io/cloud-builders/gradle'
    id: 'Gradle jib build'
    entrypoint: 'bash'
    env:
      - 'NEWV_DISCOVERY_IMAGE_REGISTRY=$NEWV_DISCOVERY_IMAGE_REGISTRY'
    args:
      - '-c'
      - |
        chmod +x ./gradlew
        ./gradlew jib