steps:

  - # Uses the Cloud Builder Gradle image since it is cached.
    name: 'gcr.io/cloud-builders/gradle'
    id: 'Cache'
    dir: /root
    entrypoint: bash
    args:
      - -c
      - |
        mkdir .docker &&
        ln -s $$HOME/.docker/config.json .docker/config.json

  - # Compiles the app and Jib build.
    name: 'gcr.io/cloud-builders/gradle'
    id: 'Gradle jib build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo registry url env
        echo $_NEWV_DISCOVERY_IMAGE_REGISTRY
        REGISTRY=${_NEWV_DISCOVERY_IMAGE_REGISTRY}
        chmod +x ./gradlew
        ./gradlew jib -Djib.to.image="$${REGISTRY}"