server:
  port: 9002

spring:
  cloud:
    config:
      uri: http://newv-config:8888
      name: newv-discovery-peer-2

eureka:
  instance:
    hostname: newv-discovery-peer-2
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://newv-discovery-peer-1:9001/eureka
