server:
  port: 9001

spring:
  cloud:
    config:
      uri: http://newv-config:8888
      name: newv-discovery-peer-1

eureka:
  instance:
    hostname: newv-discovery-peer-1
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://newv-discovery-peer-2:9002/eureka
