server:
  port: 8761
spring:
  application:
    name: newv-discovery

---

spring:
  profiles:
    active: dev
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: newv-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---

spring:
  profiles:
    active: peer-1
  cloud:
    config:
      uri: http://newv-config:8888
      name: newv-discovery-peer-1

eureka:
  client:
    serviceUrl:
      defaultZone: http://newv-discovery-peer-2:9001/eureka/

---

spring:
  profiles:
    active: peer-2
  cloud:
    config:
      uri: http://newv-config:8888
      name: newv-discovery-peer-2

eureka:
  client:
    serviceUrl:
      defaultZone: http://newv-discovery-peer-1:9001/eureka/