server:
  port: ${SERVER_PORT:8761}

spring:
  cloud:
    config:
      uri: http://${CLOUD_CONFIG_URI:localhost}:${CLOUD_CONFIG_PORT:8888}
      name: newv-discovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${EUREKA_DEFAULT_ZONE_HOST:localhost}:${EUREKA_DEFAULT_ZONE_PORT:8761}
