---
spring:
  application:
    name: newv-discovery
management:
  endpoints:
    web:
      exposure:
        include: health
---
spring:
  profiles:
    active: dev

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: newv-discovery-dev
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_DEFAULT_ZONE_HOST:localhost}:${EUREKA_DEFAULT_ZONE_PORT:8761}
